[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "16.20.2"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
